# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-Challange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Carbon'
pod 'SnapKit'
pod 'RealmSwift'
pod 'SwiftLint'
pod 'Alamofire'
pod 'Kingfisher'
  # Pods for iOS-Challange

end
